name: hexlet-ci-app.yml
on:
  - push
jobs:
  build-frontend:
  build-backend:
  test:
    needs: build-backend
  build:
    runs-on: ubuntu-latest
    steps:
      # Клонируем репозиторий
      - uses: actions/checkout@v3
      # Устанавливаем Node.js
      - uses: actions/setup-node@v3
      # Ставим зависимости
      - run: npm install
      # Запускаем линтер
      - run: npm run lint
      # Запускаем тесты
      # у шагов может быть имя, иногда это помогает отладке
      # имя выводится на Github при просмотре сборки
      - name: run tests
        run: npm test
